parts:
  - files: 
    - filename: "first_part.py"
      language: "python"
  - files:
    - filename: "second_part.py"
      language: "python"
    - filename: "rules.py"
      language: "python"
statement: "puzzle.md"
